### ISSUE TITLE
Slash commands support doesn't exist in proxy

### ISSUE THREAD

**Issue by IAmJSD** [twilight-rs/http-proxy#21]
Slash commands support does not appear to exist in this proxy.  I tried to add this myself, but I feel quite ill at the moment plus Request appears to have had some breaking changes to make it protected, so I ended up giving up for now.

**Comment by spring4175** [comment]
The `twilight-http` dependency needs updating to 0.5.

**Comment by IAmJSD** [comment]
@vivian yeah, gave it a shot locally, the protection of Request and insistence on inputting a Route made it a little frustrating though.  The whole illness thing probably doesn't help though, if nobody has got round to solving it in a few days I'll give it another shot. 👍

**Comment by spring4175** [comment]
Closing in favor of the broader issue #22.
