### ISSUE TITLE
Improve error behavior

### ISSUE THREAD

**Issue by AEnterprise** [twilight-rs/http-proxy#26]
Currently if the proxy runs into an internal error the connection is just closed without any reply. While with #25 we now have logging for these, this behavior is still far from ideal. In addition the snafu dependency is a bit redundant atm. At the very least we should be giving at least some error and not a connection reset. as this can lead to very unexpected behavior in libraries

We have several options here:
1) Return an 400 bad request, this has the clear disadvantage that downstream consumers might try to parse the body as a discord error and fail very badly, potentially crashing them
2) return a generic 500 server error
3) return a 503 service unavailable

of these option 2 and 3 would probably be the best options

**Comment by Gelbpunkt** [comment]
My suggestion based on skimming through RFC 2616:
https://github.com/twilight-rs/http-proxy/blob/trunk/src/main.rs#L271 should be 501
https://github.com/twilight-rs/http-proxy/blob/trunk/src/main.rs#L285 should be 501/500
https://github.com/twilight-rs/http-proxy/blob/trunk/src/main.rs#L298 should be 500
https://github.com/twilight-rs/http-proxy/blob/trunk/src/main.rs#L330 should be 500
https://github.com/twilight-rs/http-proxy/blob/trunk/src/main.rs#L342 should be 502
