### ISSUE TITLE
Redo documentation

### ISSUE THREAD

**Issue by Gelbpunkt** [twilight-rs/http-proxy#45]
The README is partially wrong and some features need to be documented:
* The http-proxy is *not* a "real" HTTP proxy, the ruby example needs to be removed and replaced with maybe a curl example
* Behaviour with `Authorization` header set needs to be explained better (multiple clients)
* API v8/v6 images should no longer be mentioned, latest supports all versions as long as the Path exists in twilight
* Metrics shouldn't be documented as "Grafana metrics", rather as "Prometheus metrics" since Grafana also supports e.g. InfluxDB as a backend
* After tackling #26, document this behavior properly

**Comment by 7596ff** [comment]
While you're at it, could you wrap all docs to 80 characters, so we are consistent with the main repo (in preparation for this to be folded in)
